In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

##Realizar condiciones

Las condiciones utilizando operadores nos retornarán valores booleanos

In [3]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
##Si enviamos el código de la siguiente manera, nos filtrará el array por los valores que sean positivos
indices_condicion = arr > 5
arr[indices_condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

Podemos hacer condiciones multiples, por ejemplo:

In [5]:
arr[(indices_condicion) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Podemos cambiar valores a datos que cumplan ciertas condiciones

In [6]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [8]:
##Mostrar aquellos que son iguales a 99
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)