In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##Si no se realiza la función copy, a pesar de ocupar otra variable, nuestro array original se va a modificar

In [4]:
trozo_arr = arr[0:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [5]:
##Cambiamos los valores al trozo de array por cero
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

##Si volvemos al arreglo original veremos que tambien ha sido modificado

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Generemos un nuevo array y utilicemos el comando copy para copiar el arreglo y no modificar el original

In [7]:
arr_dos = np.arange(0,11)
arr_dos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr_copy = arr_dos.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
arr_dos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])