In [1]:
import numpy as np

In [2]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [15]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.8346763106676125

In [19]:
np.random.rand(4)

array([0.73739002, 0.20207705, 0.9841753 , 0.54788063])

In [20]:
np.random.rand(4,4)

array([[0.67475019, 0.19764455, 0.82271964, 0.10970616],
       [0.49096566, 0.20625684, 0.67374132, 0.63742989],
       [0.30783022, 0.33887521, 0.58912576, 0.29963364],
       [0.88080463, 0.85456613, 0.9101131 , 0.75625098]])

In [21]:
np.random.randint(1,100)

88

In [22]:
np.random.randint(1,100,(10,10))

array([[17, 43, 51, 81, 12, 10, 77, 74, 75, 62],
       [65, 62, 49, 35, 13,  7, 41, 41, 92, 22],
       [21, 75, 64, 33,  4, 93, 22, 50, 93, 64],
       [21, 40, 72,  5,  9, 28, 13, 72, 99, 50],
       [29, 59, 23, 98, 39, 85, 81, 34, 78, 23],
       [85, 42, 54, 73,  9, 70, 60, 52, 38,  4],
       [69, 34, 16, 89, 75, 20, 79, 11, 34, 30],
       [20, 47, 72, 42,  5, 63, 88, 54, 61, 23],
       [63, 58, 50, 19, 99, 26, 73, 95, 95, 18],
       [67, 27, 83,  6, 34,  2, 74, 33, 16, 75]])