In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)

In [5]:
matriz = arr.reshape(2,5)
matriz

array([[ 8,  3,  4,  9, 15],
       [ 3, 11, 17,  4,  9]])

In [7]:
arr.max()

17

In [8]:
matriz.max()

17

In [9]:
matriz.max(1)

array([15, 17])

In [10]:
matriz.max(0)

array([ 8, 11, 17,  9, 15])

In [13]:
print(arr)
arr.argmax()

[ 8  3  4  9 15  3 11 17  4  9]


7

In [16]:
matriz.argmax()

7

In [17]:
matriz.argmax(0)

array([0, 1, 1, 0, 0])

In [19]:
arr.min()

3

In [20]:
matriz.min()

3

In [21]:
arr.argmin()

1

In [22]:
matriz.argmin()

1

In [25]:
matriz.argmin(0)

array([1, 0, 0, 1, 1])

In [27]:
print(arr)
arr.ptp()

[ 8  3  4  9 15  3 11 17  4  9]


14

In [28]:
matriz.ptp()

14

In [29]:
matriz.ptp(0)

array([ 5,  8, 13,  5,  6])

In [35]:
arr.sort()
print(arr)
np.percentile(arr,50)

[ 3  3  4  4  8  9  9 11 15 17]


8.5

In [36]:
np.median(arr)

8.5

In [38]:
np.median(matriz, 1)

array([ 4., 11.])

In [39]:
np.std(arr)

4.712748667179271

In [41]:
np.std(arr) ** 2

22.209999999999997

In [40]:
np.var(arr)

22.21

In [43]:
np.mean(arr)

8.3

In [55]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [58]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [59]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##Manejo de errores en las dimensiones de los arreglos

In [79]:
c = np.array([[1,2],[3,4]])
d = np.array([5,6])

In [69]:
##Error ocurrido debido a que los arreglos no tienen el mismo número de dimensiones
np.concatenate((c,d), axis=0)

ValueError: ignored

In [80]:
print(c.ndim)
print(d.ndim)

2
1


In [81]:
##Expandimos el número de dimensiones para que coincida con el arreglo a y poder concatenar
d = np.expand_dims(d,axis=0)

In [82]:
d

array([[5, 6]])

In [83]:
np.concatenate((c,d), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
##Dado que la lista b ahora tiene una dimensión de dos, concatenarla por el axis 1 ahora produce un error
np.concatenate((c,d), axis=1)

ValueError: ignored

In [85]:
##La T mayúscula es la transpuesta de una matriz, es decir, invertir las filas por las columnas y viceversa
np.concatenate((c,d.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])