In [ ]:
import numpy as np

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
##Multiplicar una la lista básica de python lo que nos arrojará como resultado es duplicarla en lugar de realizar la multiplicación de cada uno de sus elementos
lista * 2

[1, 2, 1, 2]

#Realización de operaciones con numpy

In [ ]:
##Para poder realizar operaciones, debemos de realizar nnuestros arreglos utilizando numpy
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Creamos una copia para evitar modificar el arreglo original
arr2 = arr.copy()

Operaciones

In [ ]:
##Ahora la operación matemática si dará cómo resultado los valores esperados
arr_sum = arr2 + 2
arr_rest = arr2 - 2
arr_mult = arr2 * 2
arr_div = arr2 / 2
print(arr_sum)
print(arr_rest)
print(arr_mult)
print(arr_div)

[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
#Operaciones entre arrays
arr + arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

Operaciones con matriz

In [ ]:
#Generamos una matriz
matriz = arr.reshape(3,3)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
##Generamos una copia para evitar modificar la matriz original y hacer operaciones entre esta y la nueva
matriz2 = matriz.copy()

In [ ]:
matriz + matriz2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Operaciones de producto punto

In [ ]:
#En ocasiones, debemos transponer una matriz para lograr realizar esta operación
matriz2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.matmul(matriz,matriz2.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [ ]:
#Otra manera de hacerlo es con la siguiente sintaxis
matriz @ matriz2.T

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])