In [1]:
import numpy as np

In [27]:
arr = np.random.randint(1,10,(2,3))
arr

array([[3, 2, 8],
       [9, 5, 4]])

In [28]:
arr.shape

(2, 3)

In [29]:
arr.reshape(6,1)

array([[3],
       [2],
       [8],
       [9],
       [5],
       [4]])

In [30]:
np.reshape(arr, (3, 2))

array([[3, 2],
       [8, 9],
       [5, 4]])

In [41]:
np.reshape(arr,(3,2),'C')

array([[3, 2],
       [8, 9],
       [5, 4]])

In [42]:
np.reshape(arr,(3,2),'F')

array([[3, 5],
       [9, 8],
       [2, 4]])

In [43]:
np.reshape(arr, (3,2),'A')

array([[3, 2],
       [8, 9],
       [5, 4]])